/**
 * Chrome Exporter
 * Generates a Chrome theme extension
 */

import {
  type ThemeConfig,
  type ExportResult,
  hslToRgb,
} from "./types";

export function exportChrome(theme: ThemeConfig): ExportResult[] {
  const { colors, displayName, author } = theme;

  // Chrome uses RGB arrays [r, g, b] for colors
  const toRgbArray = (hsl: { h: number; s: number; l: number }): [number, number, number] => {
    const { r, g, b } = hslToRgb(hsl);
    return [r, g, b];
  };

  // manifest.json for Chrome theme
  const manifest = {
    manifest_version: 3,
    version: "1.0.0",
    name: `${displayName} Theme`,
    description: `${displayName} color theme for Chrome. Generated by Theme Bundle.`,
    author: author || "Theme Bundle",
    homepage_url: "https://themebundle.com",
    theme: {
      colors: {
        // Frame (window chrome)
        frame: toRgbArray(colors.background),
        frame_inactive: toRgbArray(colors.card),
        frame_incognito: toRgbArray(colors.background),
        frame_incognito_inactive: toRgbArray(colors.card),

        // Toolbar
        toolbar: toRgbArray(colors.card),
        toolbar_button_icon: toRgbArray(colors.foreground),
        toolbar_text: toRgbArray(colors.foreground),

        // Tab
        tab_text: toRgbArray(colors.foreground),
        tab_background_text: toRgbArray(colors.mutedForeground),
        tab_background_text_inactive: toRgbArray(colors.mutedForeground),
        tab_background_text_incognito: toRgbArray(colors.mutedForeground),
        tab_background_text_incognito_inactive: toRgbArray(colors.mutedForeground),

        // Bookmarks
        bookmark_text: toRgbArray(colors.foreground),

        // New Tab Page
        ntp_background: toRgbArray(colors.background),
        ntp_text: toRgbArray(colors.foreground),
        ntp_link: toRgbArray(colors.primary),
        ntp_header: toRgbArray(colors.card),

        // Omnibox (address bar)
        omnibox_background: toRgbArray(colors.input),
        omnibox_text: toRgbArray(colors.foreground),

        // Buttons
        button_background: toRgbArray(colors.muted),
      },
      tints: {
        // Tints are HSL values where H is 0-1, S is 0-1, L is 0-1
        // -1 means "don't change"
        buttons: [colors.foreground.h / 360, colors.foreground.s / 100, 0.5],
        frame: [-1, -1, -1],
        frame_inactive: [-1, -1, -1],
        frame_incognito: [colors.primary.h / 360, 0.5, 0.3],
        frame_incognito_inactive: [colors.primary.h / 360, 0.3, 0.2],
        background_tab: [-1, -1, -1],
      },
      properties: {
        ntp_background_alignment: "center",
        ntp_background_repeat: "no-repeat",
      },
    },
  };

  // README for installation
  const readme = `# ${displayName} Theme for Chrome

## Installation

### Method 1: Developer Mode (for testing)
1. Open Chrome and go to \`chrome://extensions\`
2. Enable "Developer mode" (toggle in top right)
3. Click "Load unpacked"
4. Select this folder (the one containing manifest.json)

### Method 2: Pack Extension
1. Go to \`chrome://extensions\`
2. Enable "Developer mode"
3. Click "Pack extension"
4. Select this folder as the extension root
5. This creates a .crx file you can share

### Method 3: Chrome Web Store
1. Create a developer account at https://chrome.google.com/webstore/developer/dashboard
2. Pay the one-time $5 registration fee
3. Upload a ZIP of this folder
4. Submit for review

## Notes

- Chrome themes don't support as many color customizations as Firefox
- Some colors may appear slightly different due to Chrome's rendering
- Incognito mode uses a slightly modified version of the theme

## Theme Colors

- Background: rgb(${toRgbArray(colors.background).join(", ")})
- Foreground: rgb(${toRgbArray(colors.foreground).join(", ")})
- Primary: rgb(${toRgbArray(colors.primary).join(", ")})
- Accent: rgb(${toRgbArray(colors.accent).join(", ")})

Generated by Theme Bundle - https://themebundle.com
`;

  return [
    {
      filename: "manifest.json",
      content: JSON.stringify(manifest, null, 2),
      platform: "chrome",
    },
    {
      filename: "README.md",
      content: readme,
      platform: "chrome",
    },
  ];
}
