/**
 * Emacs Exporter
 * Generates Emacs Lisp theme file
 */

import {
  type ThemeConfig,
  type ExportResult,
  toHex,
  getAnsiColors,
  toCamelCase,
} from "./types";

export function exportEmacs(theme: ThemeConfig): ExportResult {
  const { colors, name, displayName, author } = theme;
  const ansi = getAnsiColors(colors);
  const themeName = toCamelCase(name);

  const elisp = `;;; ${name}-theme.el --- ${displayName} theme for Emacs -*- lexical-binding: t -*-

;; Author: ${author || "Theme Bundle"}
;; URL: https://themebundle.com
;; Version: 1.0.0
;; Package-Requires: ((emacs "24.1"))

;;; Commentary:
;;
;; ${displayName} theme for Emacs.
;; Generated by Theme Bundle.
;;

;;; Code:

(deftheme ${themeName}
  "${displayName} theme for Emacs.")

(let ((class '((class color) (min-colors 89)))
      ;; Color palette
      (bg        "${toHex(colors.background)}")
      (fg        "${toHex(colors.foreground)}")
      (cursor    "${toHex(colors.primary)}")
      (selection "${toHex(colors.muted)}")
      (comment   "${toHex(colors.mutedForeground)}")
      (builtin   "${toHex(ansi.magenta)}")
      (keyword   "${toHex(ansi.red)}")
      (string    "${toHex(ansi.green)}")
      (function  "${toHex(ansi.blue)}")
      (type      "${toHex(ansi.yellow)}")
      (constant  "${toHex(ansi.magenta)}")
      (variable  "${toHex(colors.foreground)}")
      (warning   "${toHex(ansi.yellow)}")
      (error     "${toHex(colors.destructive)}")
      (success   "${toHex(ansi.green)}")
      (cyan      "${toHex(ansi.cyan)}")
      (magenta   "${toHex(ansi.magenta)}")
      ;; UI colors
      (bg-alt    "${toHex(colors.card)}")
      (border    "${toHex(colors.border)}")
      (muted     "${toHex(colors.muted)}")
      (primary   "${toHex(colors.primary)}")
      (accent    "${toHex(colors.accent)}"))

  (custom-theme-set-faces
   '${themeName}

   ;; Basic faces
   \`(default ((,class (:foreground ,fg :background ,bg))))
   \`(cursor ((,class (:background ,cursor))))
   \`(region ((,class (:background ,selection))))
   \`(highlight ((,class (:background ,muted))))
   \`(fringe ((,class (:background ,bg))))
   \`(vertical-border ((,class (:foreground ,border))))
   \`(minibuffer-prompt ((,class (:foreground ,primary :weight bold))))
   \`(link ((,class (:foreground ,primary :underline t))))
   \`(link-visited ((,class (:foreground ,magenta :underline t))))
   \`(error ((,class (:foreground ,error))))
   \`(warning ((,class (:foreground ,warning))))
   \`(success ((,class (:foreground ,success))))

   ;; Mode line
   \`(mode-line ((,class (:foreground ,fg :background ,bg-alt :box (:line-width 1 :color ,border)))))
   \`(mode-line-inactive ((,class (:foreground ,comment :background ,muted :box (:line-width 1 :color ,border)))))
   \`(mode-line-buffer-id ((,class (:foreground ,primary :weight bold))))

   ;; Line numbers
   \`(line-number ((,class (:foreground ,comment :background ,bg))))
   \`(line-number-current-line ((,class (:foreground ,fg :background ,bg-alt :weight bold))))

   ;; Font lock (syntax highlighting)
   \`(font-lock-builtin-face ((,class (:foreground ,builtin))))
   \`(font-lock-comment-face ((,class (:foreground ,comment :slant italic))))
   \`(font-lock-comment-delimiter-face ((,class (:foreground ,comment :slant italic))))
   \`(font-lock-constant-face ((,class (:foreground ,constant))))
   \`(font-lock-doc-face ((,class (:foreground ,comment))))
   \`(font-lock-function-name-face ((,class (:foreground ,function))))
   \`(font-lock-keyword-face ((,class (:foreground ,keyword))))
   \`(font-lock-negation-char-face ((,class (:foreground ,error))))
   \`(font-lock-preprocessor-face ((,class (:foreground ,cyan))))
   \`(font-lock-regexp-grouping-backslash ((,class (:foreground ,magenta))))
   \`(font-lock-regexp-grouping-construct ((,class (:foreground ,magenta))))
   \`(font-lock-string-face ((,class (:foreground ,string))))
   \`(font-lock-type-face ((,class (:foreground ,type))))
   \`(font-lock-variable-name-face ((,class (:foreground ,variable))))
   \`(font-lock-warning-face ((,class (:foreground ,warning :weight bold))))

   ;; Search
   \`(isearch ((,class (:foreground ,bg :background ,primary))))
   \`(isearch-fail ((,class (:foreground ,fg :background ,error))))
   \`(lazy-highlight ((,class (:foreground ,bg :background ,accent))))

   ;; Matching
   \`(show-paren-match ((,class (:foreground ,primary :weight bold :underline t))))
   \`(show-paren-mismatch ((,class (:foreground ,error :weight bold :underline t))))

   ;; Company (auto-completion)
   \`(company-tooltip ((,class (:foreground ,fg :background ,bg-alt))))
   \`(company-tooltip-selection ((,class (:foreground ,bg :background ,primary))))
   \`(company-tooltip-common ((,class (:foreground ,primary))))
   \`(company-scrollbar-bg ((,class (:background ,muted))))
   \`(company-scrollbar-fg ((,class (:background ,primary))))

   ;; Org mode
   \`(org-level-1 ((,class (:foreground ,primary :weight bold :height 1.3))))
   \`(org-level-2 ((,class (:foreground ,function :weight bold :height 1.2))))
   \`(org-level-3 ((,class (:foreground ,type :weight bold :height 1.1))))
   \`(org-level-4 ((,class (:foreground ,string :weight bold))))
   \`(org-code ((,class (:foreground ,cyan))))
   \`(org-verbatim ((,class (:foreground ,constant))))
   \`(org-link ((,class (:foreground ,primary :underline t))))
   \`(org-todo ((,class (:foreground ,warning :weight bold))))
   \`(org-done ((,class (:foreground ,success :weight bold))))

   ;; Dired
   \`(dired-directory ((,class (:foreground ,function :weight bold))))
   \`(dired-symlink ((,class (:foreground ,cyan))))

   ;; Magit
   \`(magit-section-heading ((,class (:foreground ,primary :weight bold))))
   \`(magit-branch-local ((,class (:foreground ,cyan))))
   \`(magit-branch-remote ((,class (:foreground ,success))))
   \`(magit-diff-added ((,class (:foreground ,success))))
   \`(magit-diff-removed ((,class (:foreground ,error))))
   \`(magit-diff-context-highlight ((,class (:background ,bg-alt))))

   ;; Which-key
   \`(which-key-key-face ((,class (:foreground ,primary))))
   \`(which-key-command-description-face ((,class (:foreground ,fg))))
   \`(which-key-group-description-face ((,class (:foreground ,function))))
   ))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme '${themeName})

;;; ${name}-theme.el ends here
`;

  return {
    filename: `${name}-theme.el`,
    content: elisp,
    platform: "emacs",
  };
}
