/**
 * Firefox Exporter
 * Generates a Firefox theme extension (WebExtension)
 */

import {
  type ThemeConfig,
  type ExportResult,
  toHex,
  toKebabCase,
} from "./types";

export function exportFirefox(theme: ThemeConfig): ExportResult[] {
  const { colors, name, displayName, author } = theme;
  const extensionId = `${toKebabCase(name)}-theme@themebundle.com`;

  // manifest.json
  const manifest = {
    manifest_version: 2,
    version: "1.0.0",
    name: `${displayName} Theme`,
    description: `${displayName} color theme for Firefox. Generated by Theme Bundle.`,
    author: author || "Theme Bundle",
    homepage_url: "https://themebundle.com",
    browser_specific_settings: {
      gecko: {
        id: extensionId,
        strict_min_version: "55.0",
      },
    },
    theme: {
      colors: {
        // Toolbar
        toolbar: toHex(colors.card),
        toolbar_text: toHex(colors.foreground),
        toolbar_field: toHex(colors.input),
        toolbar_field_text: toHex(colors.foreground),
        toolbar_field_border: toHex(colors.border),
        toolbar_field_focus: toHex(colors.background),
        toolbar_field_text_focus: toHex(colors.foreground),
        toolbar_field_border_focus: toHex(colors.ring),
        toolbar_field_highlight: toHex(colors.primary),
        toolbar_field_highlight_text: toHex(colors.background),
        toolbar_bottom_separator: toHex(colors.border),
        toolbar_top_separator: toHex(colors.border),
        toolbar_vertical_separator: toHex(colors.border),

        // Frame (window background)
        frame: toHex(colors.background),
        frame_inactive: toHex(colors.card),

        // Tab bar
        tab_background_text: toHex(colors.foreground),
        tab_background_separator: toHex(colors.border),
        tab_loading: toHex(colors.primary),
        tab_line: toHex(colors.primary),
        tab_selected: toHex(colors.background),
        tab_text: toHex(colors.foreground),

        // Bookmarks
        bookmark_text: toHex(colors.foreground),

        // Icons
        icons: toHex(colors.foreground),
        icons_attention: toHex(colors.primary),

        // Popup (menus, dropdowns)
        popup: toHex(colors.popover),
        popup_text: toHex(colors.popoverForeground),
        popup_border: toHex(colors.border),
        popup_highlight: toHex(colors.primary),
        popup_highlight_text: toHex(colors.background),

        // Sidebar
        sidebar: toHex(colors.card),
        sidebar_text: toHex(colors.foreground),
        sidebar_border: toHex(colors.border),
        sidebar_highlight: toHex(colors.primary),
        sidebar_highlight_text: toHex(colors.background),

        // Buttons
        button_background_hover: toHex(colors.muted),
        button_background_active: toHex(colors.primary),

        // New tab page
        ntp_background: toHex(colors.background),
        ntp_text: toHex(colors.foreground),
      },
      properties: {
        color_scheme: colors.background.l < 50 ? "dark" : "light",
      },
    },
  };

  // README for installation
  const readme = `# ${displayName} Theme for Firefox

## Installation

### Method 1: Temporary Installation (for testing)
1. Open Firefox and go to \`about:debugging\`
2. Click "This Firefox" in the sidebar
3. Click "Load Temporary Add-on"
4. Select the \`manifest.json\` file from this folder

### Method 2: Permanent Installation
1. Zip all files in this folder (manifest.json + README.md)
2. Rename the .zip to .xpi
3. Open Firefox and go to \`about:addons\`
4. Click the gear icon > "Install Add-on From File"
5. Select the .xpi file

### Method 3: Publish to AMO
1. Create an account at https://addons.mozilla.org
2. Submit this extension for review
3. Once approved, users can install directly

## Theme Colors

- Background: ${toHex(colors.background)}
- Foreground: ${toHex(colors.foreground)}
- Primary: ${toHex(colors.primary)}
- Accent: ${toHex(colors.accent)}

Generated by Theme Bundle - https://themebundle.com
`;

  return [
    {
      filename: "manifest.json",
      content: JSON.stringify(manifest, null, 2),
      platform: "firefox",
    },
    {
      filename: "README.md",
      content: readme,
      platform: "firefox",
    },
  ];
}
