/**
 * Insomnia REST Client Exporter
 * Generates JSON theme plugin for Insomnia
 */

import {
  type ThemeConfig,
  type ExportResult,
  toHex,
  lighten,
  darken,
  toKebabCase,
} from "./types";

export function exportInsomnia(theme: ThemeConfig): ExportResult[] {
  const { colors, name, displayName, author } = theme;
  const isDark = colors.background.l < 50;
  const pluginName = `insomnia-plugin-theme-${toKebabCase(name)}`;

  // package.json for the Insomnia plugin
  const packageJson = {
    name: pluginName,
    version: "1.0.0",
    description: `${displayName} theme for Insomnia REST Client`,
    author: author || "Theme Bundle",
    homepage: "https://themebundle.com",
    main: "theme.js",
    insomnia: {
      name: `theme-${toKebabCase(name)}`,
      displayName: `${displayName} Theme`,
      description: `${displayName} color theme. Generated by Theme Bundle.`,
      publisher: {
        name: author || "Theme Bundle",
      },
    },
  };

  // theme.js - Insomnia theme module
  const themeJs = `/**
 * ${displayName} Theme for Insomnia
 * Generated by Theme Bundle - https://themebundle.com
 */

module.exports.themes = [{
  name: '${toKebabCase(name)}',
  displayName: '${displayName}',
  theme: {
    // Base colors
    background: {
      default: '${toHex(colors.background)}',
      success: '${toHex(colors.accent)}',
      notice: '${toHex({ h: 45, s: colors.primary.s, l: colors.primary.l })}',
      warning: '${toHex({ h: 30, s: 100, l: 50 })}',
      danger: '${toHex(colors.destructive)}',
      surprise: '${toHex(colors.primary)}',
      info: '${toHex(colors.accent)}',
    },
    
    // Foreground colors
    foreground: {
      default: '${toHex(colors.foreground)}',
      success: '${toHex(colors.background)}',
      notice: '${toHex(colors.background)}',
      warning: '${toHex(colors.background)}',
      danger: '${toHex(colors.background)}',
      surprise: '${toHex(colors.background)}',
      info: '${toHex(colors.background)}',
    },
    
    // Highlight colors
    highlight: {
      default: '${toHex(colors.muted)}',
      xxs: '${toHex(isDark ? lighten(colors.background, 2) : darken(colors.background, 2))}',
      xs: '${toHex(isDark ? lighten(colors.background, 5) : darken(colors.background, 5))}',
      sm: '${toHex(isDark ? lighten(colors.background, 8) : darken(colors.background, 8))}',
      md: '${toHex(isDark ? lighten(colors.background, 12) : darken(colors.background, 12))}',
      lg: '${toHex(isDark ? lighten(colors.background, 16) : darken(colors.background, 16))}',
      xl: '${toHex(isDark ? lighten(colors.background, 20) : darken(colors.background, 20))}',
    },
    
    // Styles
    styles: {
      // Dialog
      dialog: {
        background: {
          default: '${toHex(colors.popover)}',
        },
        foreground: {
          default: '${toHex(colors.popoverForeground)}',
        },
      },
      
      // Pane header
      paneHeader: {
        background: {
          default: '${toHex(colors.card)}',
          success: '${toHex(colors.accent)}',
          notice: '${toHex({ h: 45, s: colors.primary.s, l: colors.primary.l })}',
          warning: '${toHex({ h: 30, s: 100, l: 50 })}',
          danger: '${toHex(colors.destructive)}',
          surprise: '${toHex(colors.primary)}',
          info: '${toHex(colors.accent)}',
        },
        foreground: {
          default: '${toHex(colors.foreground)}',
        },
      },
      
      // Sidebar
      sidebar: {
        background: {
          default: '${toHex(colors.card)}',
        },
        foreground: {
          default: '${toHex(colors.foreground)}',
        },
        highlight: {
          default: '${toHex(colors.muted)}',
        },
      },
      
      // Sidebar header
      sidebarHeader: {
        background: {
          default: '${toHex(colors.background)}',
        },
        foreground: {
          default: '${toHex(colors.foreground)}',
        },
      },
      
      // Transparent overlay
      transparentOverlay: {
        background: {
          default: '${toHex(colors.background)}80',
        },
        foreground: {
          default: '${toHex(colors.foreground)}',
        },
      },
    },
    
    // Raw CSS (optional customizations)
    rawCss: \`
      /* Custom scrollbar */
      ::-webkit-scrollbar {
        width: 8px;
        height: 8px;
      }
      ::-webkit-scrollbar-track {
        background: ${toHex(colors.background)};
      }
      ::-webkit-scrollbar-thumb {
        background: ${toHex(colors.muted)};
        border-radius: 4px;
      }
      ::-webkit-scrollbar-thumb:hover {
        background: ${toHex(colors.mutedForeground)};
      }
    \`,
  },
}];
`;

  // README
  const readme = `# ${displayName} Theme for Insomnia

## Installation

### Method 1: Plugin Folder
1. Open Insomnia
2. Go to Application > Preferences > Plugins
3. Click "Reveal Plugins Folder"
4. Copy this entire folder into the plugins directory
5. Click "Reload Plugins" in Insomnia

### Method 2: npm (if publishing)
\`\`\`bash
# From Insomnia's plugin folder
npm install ${pluginName}
\`\`\`

## Usage

1. After installation, go to Application > Preferences > Themes
2. Select "${displayName}" from the theme list

## Files

- \`package.json\` - Plugin metadata
- \`theme.js\` - Theme definition

Generated by Theme Bundle - https://themebundle.com
`;

  return [
    {
      filename: "package.json",
      content: JSON.stringify(packageJson, null, 2),
      platform: "insomnia",
    },
    {
      filename: "theme.js",
      content: themeJs,
      platform: "insomnia",
    },
    {
      filename: "README.md",
      content: readme,
      platform: "insomnia",
    },
  ];
}
