/**
 * JetBrains IDEs Exporter
 * Generates .icls XML color scheme file for IntelliJ, WebStorm, PyCharm, etc.
 */

import {
  type ThemeConfig,
  type ExportResult,
  toHexRaw,
  getAnsiColors,
  escapeXml,
} from "./types";

export function exportJetbrains(theme: ThemeConfig): ExportResult {
  const { colors, name, displayName } = theme;
  const ansi = getAnsiColors(colors);
  const isDark = colors.background.l < 50;

  // JetBrains uses RRGGBB format without #
  const color = (hsl: { h: number; s: number; l: number }) => toHexRaw(hsl).toUpperCase();

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  ${escapeXml(displayName)} theme for JetBrains IDEs
  Generated by Theme Bundle
  
  Installation:
  1. Open Settings/Preferences > Editor > Color Scheme
  2. Click the gear icon > Import Scheme
  3. Select this file
-->
<scheme name="${escapeXml(displayName)}" version="142" parent_scheme="${isDark ? "Darcula" : "Default"}">
  <metaInfo>
    <property name="created">Theme Bundle</property>
    <property name="ide">Idea</property>
    <property name="ideVersion">2023.1</property>
    <property name="modified">Theme Bundle</property>
    <property name="originalScheme">${escapeXml(displayName)}</property>
  </metaInfo>
  <colors>
    <!-- Editor -->
    <option name="CARET_COLOR" value="${color(colors.primary)}" />
    <option name="CARET_ROW_COLOR" value="${color(colors.card)}" />
    <option name="CONSOLE_BACKGROUND_KEY" value="${color(colors.background)}" />
    <option name="GUTTER_BACKGROUND" value="${color(colors.background)}" />
    <option name="INDENT_GUIDE" value="${color(colors.border)}" />
    <option name="LINE_NUMBERS_COLOR" value="${color(colors.mutedForeground)}" />
    <option name="RIGHT_MARGIN_COLOR" value="${color(colors.border)}" />
    <option name="SELECTION_BACKGROUND" value="${color(colors.muted)}" />
    <option name="SELECTION_FOREGROUND" value="${color(colors.foreground)}" />
    <option name="WHITESPACES" value="${color(colors.mutedForeground)}" />
    
    <!-- Search -->
    <option name="SEARCH_RESULT_ATTRIBUTES" value="${color(colors.accent)}" />
    <option name="TEXT_SEARCH_RESULT_ATTRIBUTES" value="${color(colors.accent)}" />
    <option name="WRITE_SEARCH_RESULT_ATTRIBUTES" value="${color(colors.primary)}" />
    
    <!-- VCS -->
    <option name="ADDED_LINES_COLOR" value="${color(ansi.green)}" />
    <option name="DELETED_LINES_COLOR" value="${color(ansi.red)}" />
    <option name="MODIFIED_LINES_COLOR" value="${color(ansi.yellow)}" />
    
    <!-- Diff -->
    <option name="DIFF_INSERTED" value="${color(ansi.green)}" />
    <option name="DIFF_DELETED" value="${color(ansi.red)}" />
    <option name="DIFF_MODIFIED" value="${color(ansi.yellow)}" />
    
    <!-- Terminal -->
    <option name="TERMINAL_COMMAND_TO_RUN_USING_IDE_VALUE" value="${color(colors.primary)}" />
  </colors>
  <attributes>
    <!-- Default text -->
    <option name="TEXT">
      <value>
        <option name="FOREGROUND" value="${color(colors.foreground)}" />
        <option name="BACKGROUND" value="${color(colors.background)}" />
      </value>
    </option>
    
    <!-- Comments -->
    <option name="DEFAULT_LINE_COMMENT">
      <value>
        <option name="FOREGROUND" value="${color(colors.mutedForeground)}" />
        <option name="FONT_TYPE" value="2" />
      </value>
    </option>
    <option name="DEFAULT_BLOCK_COMMENT">
      <value>
        <option name="FOREGROUND" value="${color(colors.mutedForeground)}" />
        <option name="FONT_TYPE" value="2" />
      </value>
    </option>
    <option name="DEFAULT_DOC_COMMENT">
      <value>
        <option name="FOREGROUND" value="${color(colors.mutedForeground)}" />
        <option name="FONT_TYPE" value="2" />
      </value>
    </option>
    
    <!-- Strings -->
    <option name="DEFAULT_STRING">
      <value>
        <option name="FOREGROUND" value="${color(ansi.green)}" />
      </value>
    </option>
    
    <!-- Numbers -->
    <option name="DEFAULT_NUMBER">
      <value>
        <option name="FOREGROUND" value="${color(ansi.magenta)}" />
      </value>
    </option>
    
    <!-- Keywords -->
    <option name="DEFAULT_KEYWORD">
      <value>
        <option name="FOREGROUND" value="${color(ansi.red)}" />
      </value>
    </option>
    
    <!-- Functions -->
    <option name="DEFAULT_FUNCTION_DECLARATION">
      <value>
        <option name="FOREGROUND" value="${color(ansi.blue)}" />
      </value>
    </option>
    <option name="DEFAULT_FUNCTION_CALL">
      <value>
        <option name="FOREGROUND" value="${color(ansi.blue)}" />
      </value>
    </option>
    
    <!-- Classes -->
    <option name="DEFAULT_CLASS_NAME">
      <value>
        <option name="FOREGROUND" value="${color(ansi.yellow)}" />
      </value>
    </option>
    <option name="DEFAULT_INTERFACE_NAME">
      <value>
        <option name="FOREGROUND" value="${color(ansi.yellow)}" />
      </value>
    </option>
    
    <!-- Variables -->
    <option name="DEFAULT_LOCAL_VARIABLE">
      <value>
        <option name="FOREGROUND" value="${color(colors.foreground)}" />
      </value>
    </option>
    <option name="DEFAULT_PARAMETER">
      <value>
        <option name="FOREGROUND" value="${color(colors.foreground)}" />
      </value>
    </option>
    <option name="DEFAULT_INSTANCE_FIELD">
      <value>
        <option name="FOREGROUND" value="${color(ansi.cyan)}" />
      </value>
    </option>
    <option name="DEFAULT_STATIC_FIELD">
      <value>
        <option name="FOREGROUND" value="${color(ansi.cyan)}" />
        <option name="FONT_TYPE" value="2" />
      </value>
    </option>
    
    <!-- Constants -->
    <option name="DEFAULT_CONSTANT">
      <value>
        <option name="FOREGROUND" value="${color(ansi.magenta)}" />
      </value>
    </option>
    
    <!-- Operators -->
    <option name="DEFAULT_OPERATION_SIGN">
      <value>
        <option name="FOREGROUND" value="${color(colors.foreground)}" />
      </value>
    </option>
    
    <!-- Brackets -->
    <option name="DEFAULT_BRACKETS">
      <value>
        <option name="FOREGROUND" value="${color(colors.foreground)}" />
      </value>
    </option>
    <option name="DEFAULT_PARENTHS">
      <value>
        <option name="FOREGROUND" value="${color(colors.foreground)}" />
      </value>
    </option>
    <option name="DEFAULT_BRACES">
      <value>
        <option name="FOREGROUND" value="${color(colors.foreground)}" />
      </value>
    </option>
    
    <!-- Errors/Warnings -->
    <option name="ERRORS_ATTRIBUTES">
      <value>
        <option name="EFFECT_COLOR" value="${color(colors.destructive)}" />
        <option name="ERROR_STRIPE_COLOR" value="${color(colors.destructive)}" />
        <option name="EFFECT_TYPE" value="2" />
      </value>
    </option>
    <option name="WARNING_ATTRIBUTES">
      <value>
        <option name="EFFECT_COLOR" value="${color(ansi.yellow)}" />
        <option name="ERROR_STRIPE_COLOR" value="${color(ansi.yellow)}" />
        <option name="EFFECT_TYPE" value="2" />
      </value>
    </option>
    
    <!-- HTML/XML -->
    <option name="HTML_TAG_NAME">
      <value>
        <option name="FOREGROUND" value="${color(ansi.red)}" />
      </value>
    </option>
    <option name="HTML_ATTRIBUTE_NAME">
      <value>
        <option name="FOREGROUND" value="${color(ansi.yellow)}" />
      </value>
    </option>
    <option name="HTML_ATTRIBUTE_VALUE">
      <value>
        <option name="FOREGROUND" value="${color(ansi.green)}" />
      </value>
    </option>
    
    <!-- Markdown -->
    <option name="MARKDOWN_HEADER">
      <value>
        <option name="FOREGROUND" value="${color(ansi.blue)}" />
        <option name="FONT_TYPE" value="1" />
      </value>
    </option>
    <option name="MARKDOWN_LINK_TEXT">
      <value>
        <option name="FOREGROUND" value="${color(colors.primary)}" />
        <option name="EFFECT_TYPE" value="1" />
      </value>
    </option>
    <option name="MARKDOWN_CODE_SPAN">
      <value>
        <option name="FOREGROUND" value="${color(ansi.cyan)}" />
      </value>
    </option>
  </attributes>
</scheme>
`;

  return {
    filename: `${name}.icls`,
    content: xml,
    platform: "jetbrains",
  };
}
