/**
 * Notepad++ Exporter
 * Generates XML theme file for Notepad++
 */

import {
  type ThemeConfig,
  type ExportResult,
  hslToRgb,
  getAnsiColors,
  escapeXml,
} from "./types";

// Notepad++ uses BGR format as decimal
function toBgr(hsl: { h: number; s: number; l: number }): number {
  const { r, g, b } = hslToRgb(hsl);
  return b * 65536 + g * 256 + r;
}

export function exportNotepadPlusPlus(theme: ThemeConfig): ExportResult {
  const { colors, name, displayName } = theme;
  const ansi = getAnsiColors(colors);

  const xml = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  ${escapeXml(displayName)} theme for Notepad++
  Generated by Theme Bundle
  
  Installation:
  1. Save this file to: %APPDATA%\\Notepad++\\themes\\
  2. Restart Notepad++
  3. Settings > Style Configurator > Select theme
-->
<NotepadPlus>
  <LexerStyles>
    <!-- Global Styles -->
    <LexerType name="Global Styles">
      <WordsStyle name="Default Style" styleID="0" fgColor="${toBgr(colors.foreground)}" bgColor="${toBgr(colors.background)}" />
      <WordsStyle name="Line number margin" styleID="33" fgColor="${toBgr(colors.mutedForeground)}" bgColor="${toBgr(colors.background)}" />
      <WordsStyle name="Brace highlight style" styleID="34" fgColor="${toBgr(colors.primary)}" bgColor="${toBgr(colors.background)}" fontStyle="1" />
      <WordsStyle name="Brace bad colour" styleID="35" fgColor="${toBgr(colors.destructive)}" bgColor="${toBgr(colors.background)}" />
      <WordsStyle name="Current line background colour" styleID="0" bgColor="${toBgr(colors.card)}" />
      <WordsStyle name="Selected text colour" styleID="0" bgColor="${toBgr(colors.muted)}" />
      <WordsStyle name="Caret colour" styleID="2069" fgColor="${toBgr(colors.primary)}" />
      <WordsStyle name="Edge colour" styleID="0" fgColor="${toBgr(colors.border)}" />
      <WordsStyle name="Fold margin" styleID="0" fgColor="${toBgr(colors.mutedForeground)}" bgColor="${toBgr(colors.background)}" />
      <WordsStyle name="Fold" styleID="0" fgColor="${toBgr(colors.mutedForeground)}" bgColor="${toBgr(colors.background)}" />
      <WordsStyle name="White space symbol" styleID="0" fgColor="${toBgr(colors.mutedForeground)}" />
      <WordsStyle name="Smart HighLighting" styleID="29" bgColor="${toBgr(colors.accent)}" />
      <WordsStyle name="Find Mark Style" styleID="31" bgColor="${toBgr(colors.accent)}" />
      <WordsStyle name="Mark Style 1" styleID="25" bgColor="${toBgr(ansi.red)}" />
      <WordsStyle name="Mark Style 2" styleID="24" bgColor="${toBgr(ansi.green)}" />
      <WordsStyle name="Mark Style 3" styleID="23" bgColor="${toBgr(ansi.yellow)}" />
      <WordsStyle name="Mark Style 4" styleID="22" bgColor="${toBgr(ansi.blue)}" />
      <WordsStyle name="Mark Style 5" styleID="21" bgColor="${toBgr(ansi.magenta)}" />
      <WordsStyle name="Incremental highlight all" styleID="28" bgColor="${toBgr(colors.primary)}" />
      <WordsStyle name="URL hovered" styleID="0" fgColor="${toBgr(colors.primary)}" />
    </LexerType>

    <!-- C/C++ -->
    <LexerType name="C" desc="C/C++">
      <WordsStyle name="DEFAULT" styleID="11" fgColor="${toBgr(colors.foreground)}" bgColor="${toBgr(colors.background)}" />
      <WordsStyle name="COMMENT" styleID="1" fgColor="${toBgr(colors.mutedForeground)}" fontStyle="2" />
      <WordsStyle name="COMMENT LINE" styleID="2" fgColor="${toBgr(colors.mutedForeground)}" fontStyle="2" />
      <WordsStyle name="COMMENT DOC" styleID="3" fgColor="${toBgr(colors.mutedForeground)}" fontStyle="2" />
      <WordsStyle name="NUMBER" styleID="4" fgColor="${toBgr(ansi.magenta)}" />
      <WordsStyle name="INSTRUCTION WORD" styleID="5" fgColor="${toBgr(ansi.red)}" />
      <WordsStyle name="TYPE WORD" styleID="16" fgColor="${toBgr(ansi.yellow)}" />
      <WordsStyle name="STRING" styleID="6" fgColor="${toBgr(ansi.green)}" />
      <WordsStyle name="CHARACTER" styleID="7" fgColor="${toBgr(ansi.green)}" />
      <WordsStyle name="PREPROCESSOR" styleID="9" fgColor="${toBgr(ansi.cyan)}" />
      <WordsStyle name="OPERATOR" styleID="10" fgColor="${toBgr(colors.foreground)}" />
      <WordsStyle name="FUNCTION" styleID="20" fgColor="${toBgr(ansi.blue)}" />
    </LexerType>

    <!-- JavaScript -->
    <LexerType name="javascript.js" desc="JavaScript">
      <WordsStyle name="DEFAULT" styleID="41" fgColor="${toBgr(colors.foreground)}" bgColor="${toBgr(colors.background)}" />
      <WordsStyle name="COMMENT" styleID="42" fgColor="${toBgr(colors.mutedForeground)}" fontStyle="2" />
      <WordsStyle name="COMMENT LINE" styleID="43" fgColor="${toBgr(colors.mutedForeground)}" fontStyle="2" />
      <WordsStyle name="COMMENT DOC" styleID="44" fgColor="${toBgr(colors.mutedForeground)}" fontStyle="2" />
      <WordsStyle name="NUMBER" styleID="45" fgColor="${toBgr(ansi.magenta)}" />
      <WordsStyle name="WORD" styleID="46" fgColor="${toBgr(ansi.red)}" />
      <WordsStyle name="KEYWORD" styleID="47" fgColor="${toBgr(ansi.red)}" />
      <WordsStyle name="STRING" styleID="48" fgColor="${toBgr(ansi.green)}" />
      <WordsStyle name="CHARACTER" styleID="52" fgColor="${toBgr(ansi.green)}" />
      <WordsStyle name="OPERATOR" styleID="49" fgColor="${toBgr(colors.foreground)}" />
      <WordsStyle name="REGEX" styleID="50" fgColor="${toBgr(ansi.cyan)}" />
    </LexerType>

    <!-- Python -->
    <LexerType name="python" desc="Python">
      <WordsStyle name="DEFAULT" styleID="0" fgColor="${toBgr(colors.foreground)}" bgColor="${toBgr(colors.background)}" />
      <WordsStyle name="COMMENT" styleID="1" fgColor="${toBgr(colors.mutedForeground)}" fontStyle="2" />
      <WordsStyle name="NUMBER" styleID="2" fgColor="${toBgr(ansi.magenta)}" />
      <WordsStyle name="STRING" styleID="3" fgColor="${toBgr(ansi.green)}" />
      <WordsStyle name="STRING DOUBLE" styleID="4" fgColor="${toBgr(ansi.green)}" />
      <WordsStyle name="KEYWORD" styleID="5" fgColor="${toBgr(ansi.red)}" />
      <WordsStyle name="TRIPLE SINGLE" styleID="6" fgColor="${toBgr(ansi.green)}" />
      <WordsStyle name="TRIPLE DOUBLE" styleID="7" fgColor="${toBgr(ansi.green)}" />
      <WordsStyle name="CLASSNAME" styleID="8" fgColor="${toBgr(ansi.yellow)}" />
      <WordsStyle name="DEFNAME" styleID="9" fgColor="${toBgr(ansi.blue)}" />
      <WordsStyle name="OPERATOR" styleID="10" fgColor="${toBgr(colors.foreground)}" />
      <WordsStyle name="DECORATOR" styleID="15" fgColor="${toBgr(ansi.cyan)}" />
    </LexerType>

    <!-- HTML -->
    <LexerType name="html" desc="HTML">
      <WordsStyle name="DEFAULT" styleID="0" fgColor="${toBgr(colors.foreground)}" bgColor="${toBgr(colors.background)}" />
      <WordsStyle name="TAG" styleID="1" fgColor="${toBgr(ansi.red)}" />
      <WordsStyle name="TAGUNKNOWN" styleID="2" fgColor="${toBgr(ansi.red)}" />
      <WordsStyle name="ATTRIBUTE" styleID="3" fgColor="${toBgr(ansi.yellow)}" />
      <WordsStyle name="ATTRIBUTEUNKNOWN" styleID="4" fgColor="${toBgr(ansi.yellow)}" />
      <WordsStyle name="NUMBER" styleID="5" fgColor="${toBgr(ansi.magenta)}" />
      <WordsStyle name="DOUBLESTRING" styleID="6" fgColor="${toBgr(ansi.green)}" />
      <WordsStyle name="SINGLESTRING" styleID="7" fgColor="${toBgr(ansi.green)}" />
      <WordsStyle name="COMMENT" styleID="9" fgColor="${toBgr(colors.mutedForeground)}" fontStyle="2" />
      <WordsStyle name="ENTITY" styleID="10" fgColor="${toBgr(ansi.magenta)}" />
    </LexerType>

    <!-- CSS -->
    <LexerType name="css" desc="CSS">
      <WordsStyle name="DEFAULT" styleID="0" fgColor="${toBgr(colors.foreground)}" bgColor="${toBgr(colors.background)}" />
      <WordsStyle name="TAG" styleID="1" fgColor="${toBgr(ansi.red)}" />
      <WordsStyle name="CLASS" styleID="2" fgColor="${toBgr(ansi.yellow)}" />
      <WordsStyle name="ID" styleID="4" fgColor="${toBgr(ansi.blue)}" />
      <WordsStyle name="OPERATOR" styleID="5" fgColor="${toBgr(colors.foreground)}" />
      <WordsStyle name="IDENTIFIER" styleID="6" fgColor="${toBgr(ansi.cyan)}" />
      <WordsStyle name="VALUE" styleID="12" fgColor="${toBgr(ansi.green)}" />
      <WordsStyle name="COMMENT" styleID="9" fgColor="${toBgr(colors.mutedForeground)}" fontStyle="2" />
      <WordsStyle name="DIRECTIVE" styleID="14" fgColor="${toBgr(ansi.magenta)}" />
    </LexerType>

    <!-- Markdown -->
    <LexerType name="markdown" desc="Markdown">
      <WordsStyle name="DEFAULT" styleID="0" fgColor="${toBgr(colors.foreground)}" bgColor="${toBgr(colors.background)}" />
      <WordsStyle name="LINE BEGIN" styleID="1" fgColor="${toBgr(colors.foreground)}" />
      <WordsStyle name="STRONG1" styleID="2" fgColor="${toBgr(colors.foreground)}" fontStyle="1" />
      <WordsStyle name="STRONG2" styleID="3" fgColor="${toBgr(colors.foreground)}" fontStyle="1" />
      <WordsStyle name="EM1" styleID="4" fgColor="${toBgr(colors.foreground)}" fontStyle="2" />
      <WordsStyle name="EM2" styleID="5" fgColor="${toBgr(colors.foreground)}" fontStyle="2" />
      <WordsStyle name="HEADER1" styleID="6" fgColor="${toBgr(ansi.blue)}" fontStyle="1" />
      <WordsStyle name="HEADER2" styleID="7" fgColor="${toBgr(ansi.blue)}" fontStyle="1" />
      <WordsStyle name="HEADER3" styleID="8" fgColor="${toBgr(ansi.blue)}" fontStyle="1" />
      <WordsStyle name="PRECHAR" styleID="9" fgColor="${toBgr(ansi.cyan)}" />
      <WordsStyle name="ULIST_ITEM" styleID="10" fgColor="${toBgr(colors.primary)}" />
      <WordsStyle name="OLIST_ITEM" styleID="11" fgColor="${toBgr(colors.primary)}" />
      <WordsStyle name="LINK" styleID="14" fgColor="${toBgr(colors.primary)}" />
      <WordsStyle name="CODE" styleID="17" fgColor="${toBgr(ansi.cyan)}" />
      <WordsStyle name="CODE2" styleID="18" fgColor="${toBgr(ansi.cyan)}" />
      <WordsStyle name="CODEBLOCK" styleID="19" fgColor="${toBgr(ansi.cyan)}" />
    </LexerType>
  </LexerStyles>
</NotepadPlus>
`;

  return {
    filename: `${name}.xml`,
    content: xml,
    platform: "notepad-plus-plus",
  };
}
