/**
 * Raycast Exporter
 * Generates JSON theme for Raycast launcher (macOS)
 */

import {
  type ThemeConfig,
  type ExportResult,
  toHex,
} from "./types";

export function exportRaycast(theme: ThemeConfig): ExportResult {
  const { colors, name, displayName, author } = theme;
  const isDark = colors.background.l < 50;

  const content = `{
  "$schema": "https://www.raycast.com/schemas/theme.json",
  "name": "${displayName}",
  "author": "${author || "Theme Bundle"}",
  "authorUsername": "themebundle",
  "version": "1.0.0",
  "description": "${displayName} color theme for Raycast. Generated by Theme Bundle.",
  "appearance": "${isDark ? "dark" : "light"}",
  "colors": {
    "background": "${toHex(colors.background)}",
    "backgroundSecondary": "${toHex(colors.card)}",
    "text": "${toHex(colors.foreground)}",
    "textSecondary": "${toHex(colors.mutedForeground)}",
    "tint": "${toHex(colors.primary)}",
    "selection": "${toHex(colors.muted)}",
    "loader": "${toHex(colors.primary)}",
    "red": "${toHex(colors.destructive)}",
    "orange": "${toHex({ h: 30, s: 100, l: 50 })}",
    "yellow": "${toHex({ h: 45, s: colors.primary.s, l: colors.primary.l })}",
    "green": "${toHex(colors.accent)}",
    "blue": "${toHex(colors.primary)}",
    "purple": "${toHex({ h: 270, s: colors.primary.s, l: colors.primary.l })}",
    "magenta": "${toHex({ h: 300, s: colors.primary.s, l: colors.primary.l })}"
  }
}

/*
 * ${displayName} Theme for Raycast
 * 
 * ## Installation
 * 
 * 1. Open Raycast
 * 2. Open Settings (Cmd + ,)
 * 3. Go to "Appearance" tab
 * 4. Click "Add Theme" or "Import Theme"
 * 5. Select this JSON file
 * 
 * ## Alternative: Manual Installation
 * 
 * 1. Copy the JSON above (without these comments)
 * 2. Save as "${name}.raycasttheme"
 * 3. Double-click the file to import into Raycast
 * 
 * ## Notes
 * 
 * - Raycast themes are simple and focus on the main launcher UI
 * - Some extensions may have their own color schemes
 * - The theme will apply to all Raycast windows and menus
 * 
 * Generated by Theme Bundle - https://themebundle.com
 */
`;

  return {
    filename: `${name}.raycasttheme`,
    content,
    platform: "raycast",
  };
}
