/**
 * Slack Exporter
 * Generates sidebar theme string for Slack
 */

import {
  type ThemeConfig,
  type ExportResult,
  toHex,
} from "./types";

export function exportSlack(theme: ThemeConfig): ExportResult {
  const { colors, name, displayName } = theme;

  // Slack sidebar theme format (comma-separated hex colors):
  // 1. Column BG (sidebar background)
  // 2. Menu BG Hover
  // 3. Active Item
  // 4. Active Item Text
  // 5. Hover Item
  // 6. Text Color
  // 7. Active Presence (online indicator)
  // 8. Mention Badge

  const themeString = [
    toHex(colors.card),           // Column BG
    toHex(colors.muted),          // Menu BG Hover
    toHex(colors.primary),        // Active Item
    toHex(colors.background),     // Active Item Text
    toHex(colors.muted),          // Hover Item
    toHex(colors.foreground),     // Text Color
    toHex(colors.accent),         // Active Presence
    toHex(colors.destructive),    // Mention Badge
  ].join(",");

  const content = `# ${displayName} Theme for Slack

## How to Apply

1. Open Slack
2. Go to Preferences (Cmd/Ctrl + ,)
3. Click on "Themes" in the sidebar
4. Scroll down to "Colors" section
5. Click "Create a custom theme"
6. Paste the theme string below

## Theme String

${themeString}

## Color Reference

| Element | Color | Hex |
|---------|-------|-----|
| Sidebar Background | 🟦 | ${toHex(colors.card)} |
| Hover Background | 🟦 | ${toHex(colors.muted)} |
| Active Item | 🟦 | ${toHex(colors.primary)} |
| Active Item Text | 🟦 | ${toHex(colors.background)} |
| Hover Item | 🟦 | ${toHex(colors.muted)} |
| Text Color | 🟦 | ${toHex(colors.foreground)} |
| Online Indicator | 🟦 | ${toHex(colors.accent)} |
| Mention Badge | 🟦 | ${toHex(colors.destructive)} |

## Notes

- Slack's theme system only affects the sidebar
- The main chat area uses Slack's default colors
- Custom themes may look different in compact vs. default density

Generated by Theme Bundle - https://themebundle.com
`;

  return {
    filename: `${name}-slack-theme.txt`,
    content,
    platform: "slack",
  };
}
