/**
 * Xcode Exporter
 * Generates .xccolortheme file for Xcode
 */

import {
  type ThemeConfig,
  type ExportResult,
  hslToRgbNormalized,
  getAnsiColors,
  escapeXml,
} from "./types";

function colorValue(hsl: { h: number; s: number; l: number }, alpha: number = 1): string {
  const { r, g, b } = hslToRgbNormalized(hsl);
  return `${r.toFixed(6)} ${g.toFixed(6)} ${b.toFixed(6)} ${alpha.toFixed(6)}`;
}

export function exportXcode(theme: ThemeConfig): ExportResult {
  const { colors, name, displayName } = theme;
  const ansi = getAnsiColors(colors);

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
  ${escapeXml(displayName)} theme for Xcode
  Generated by Theme Bundle
  
  Installation:
  1. Save to: ~/Library/Developer/Xcode/UserData/FontAndColorThemes/
  2. Restart Xcode
  3. Preferences > Fonts & Colors > Select theme
-->
<plist version="1.0">
<dict>
	<key>DVTConsoleDebuggerInputTextColor</key>
	<string>${colorValue(colors.foreground)}</string>
	<key>DVTConsoleDebuggerInputTextFont</key>
	<string>SFMono-Regular - 11.0</string>
	<key>DVTConsoleDebuggerOutputTextColor</key>
	<string>${colorValue(colors.foreground)}</string>
	<key>DVTConsoleDebuggerOutputTextFont</key>
	<string>SFMono-Regular - 11.0</string>
	<key>DVTConsoleDebuggerPromptTextColor</key>
	<string>${colorValue(colors.primary)}</string>
	<key>DVTConsoleDebuggerPromptTextFont</key>
	<string>SFMono-Bold - 11.0</string>
	<key>DVTConsoleExectuableInputTextColor</key>
	<string>${colorValue(colors.foreground)}</string>
	<key>DVTConsoleExectuableInputTextFont</key>
	<string>SFMono-Regular - 11.0</string>
	<key>DVTConsoleExectuableOutputTextColor</key>
	<string>${colorValue(colors.foreground)}</string>
	<key>DVTConsoleExectuableOutputTextFont</key>
	<string>SFMono-Regular - 11.0</string>
	<key>DVTConsoleTextBackgroundColor</key>
	<string>${colorValue(colors.background)}</string>
	<key>DVTConsoleTextInsertionPointColor</key>
	<string>${colorValue(colors.primary)}</string>
	<key>DVTConsoleTextSelectionColor</key>
	<string>${colorValue(colors.muted)}</string>
	<key>DVTDebuggerInstructionPointerColor</key>
	<string>${colorValue(ansi.green)}</string>
	<key>DVTFontAndColorVersion</key>
	<integer>1</integer>
	<key>DVTLineSpacing</key>
	<real>1.1</real>
	<key>DVTMarkupTextBackgroundColor</key>
	<string>${colorValue(colors.card)}</string>
	<key>DVTMarkupTextBorderColor</key>
	<string>${colorValue(colors.border)}</string>
	<key>DVTMarkupTextCodeFont</key>
	<string>SFMono-Regular - 11.0</string>
	<key>DVTMarkupTextInlineCodeColor</key>
	<string>${colorValue(ansi.cyan)}</string>
	<key>DVTMarkupTextLinkColor</key>
	<string>${colorValue(colors.primary)}</string>
	<key>DVTMarkupTextNormalColor</key>
	<string>${colorValue(colors.foreground)}</string>
	<key>DVTMarkupTextNormalFont</key>
	<string>.AppleSystemUIFont - 11.0</string>
	<key>DVTMarkupTextOtherHeadingColor</key>
	<string>${colorValue(ansi.blue)}</string>
	<key>DVTMarkupTextOtherHeadingFont</key>
	<string>.AppleSystemUIFontBold - 14.0</string>
	<key>DVTMarkupTextPrimaryHeadingColor</key>
	<string>${colorValue(ansi.blue)}</string>
	<key>DVTMarkupTextPrimaryHeadingFont</key>
	<string>.AppleSystemUIFontBold - 24.0</string>
	<key>DVTMarkupTextSecondaryHeadingColor</key>
	<string>${colorValue(ansi.blue)}</string>
	<key>DVTMarkupTextSecondaryHeadingFont</key>
	<string>.AppleSystemUIFontBold - 18.0</string>
	<key>DVTScrollbarMarkerAnalyzerColor</key>
	<string>${colorValue(ansi.yellow)}</string>
	<key>DVTScrollbarMarkerBreakpointColor</key>
	<string>${colorValue(ansi.blue)}</string>
	<key>DVTScrollbarMarkerDiffColor</key>
	<string>${colorValue(colors.primary)}</string>
	<key>DVTScrollbarMarkerDiffConflictColor</key>
	<string>${colorValue(colors.destructive)}</string>
	<key>DVTScrollbarMarkerErrorColor</key>
	<string>${colorValue(colors.destructive)}</string>
	<key>DVTScrollbarMarkerRuntimeIssueColor</key>
	<string>${colorValue(ansi.magenta)}</string>
	<key>DVTScrollbarMarkerWarningColor</key>
	<string>${colorValue(ansi.yellow)}</string>
	<key>DVTSourceTextBackground</key>
	<string>${colorValue(colors.background)}</string>
	<key>DVTSourceTextBlockDimBackgroundColor</key>
	<string>${colorValue(colors.muted, 0.5)}</string>
	<key>DVTSourceTextCurrentLineHighlightColor</key>
	<string>${colorValue(colors.card)}</string>
	<key>DVTSourceTextInsertionPointColor</key>
	<string>${colorValue(colors.primary)}</string>
	<key>DVTSourceTextInvisiblesColor</key>
	<string>${colorValue(colors.mutedForeground, 0.5)}</string>
	<key>DVTSourceTextSelectionColor</key>
	<string>${colorValue(colors.muted)}</string>
	<key>DVTSourceTextSyntaxColors</key>
	<dict>
		<key>xcode.syntax.attribute</key>
		<string>${colorValue(ansi.cyan)}</string>
		<key>xcode.syntax.character</key>
		<string>${colorValue(ansi.green)}</string>
		<key>xcode.syntax.comment</key>
		<string>${colorValue(colors.mutedForeground)}</string>
		<key>xcode.syntax.comment.doc</key>
		<string>${colorValue(colors.mutedForeground)}</string>
		<key>xcode.syntax.comment.doc.keyword</key>
		<string>${colorValue(colors.mutedForeground)}</string>
		<key>xcode.syntax.declaration.other</key>
		<string>${colorValue(ansi.cyan)}</string>
		<key>xcode.syntax.declaration.type</key>
		<string>${colorValue(ansi.yellow)}</string>
		<key>xcode.syntax.identifier.class</key>
		<string>${colorValue(ansi.yellow)}</string>
		<key>xcode.syntax.identifier.class.system</key>
		<string>${colorValue(ansi.magenta)}</string>
		<key>xcode.syntax.identifier.constant</key>
		<string>${colorValue(ansi.cyan)}</string>
		<key>xcode.syntax.identifier.constant.system</key>
		<string>${colorValue(ansi.magenta)}</string>
		<key>xcode.syntax.identifier.function</key>
		<string>${colorValue(ansi.blue)}</string>
		<key>xcode.syntax.identifier.function.system</key>
		<string>${colorValue(ansi.magenta)}</string>
		<key>xcode.syntax.identifier.macro</key>
		<string>${colorValue(ansi.cyan)}</string>
		<key>xcode.syntax.identifier.macro.system</key>
		<string>${colorValue(ansi.magenta)}</string>
		<key>xcode.syntax.identifier.type</key>
		<string>${colorValue(ansi.yellow)}</string>
		<key>xcode.syntax.identifier.type.system</key>
		<string>${colorValue(ansi.magenta)}</string>
		<key>xcode.syntax.identifier.variable</key>
		<string>${colorValue(colors.foreground)}</string>
		<key>xcode.syntax.identifier.variable.system</key>
		<string>${colorValue(ansi.magenta)}</string>
		<key>xcode.syntax.keyword</key>
		<string>${colorValue(ansi.red)}</string>
		<key>xcode.syntax.mark</key>
		<string>${colorValue(colors.mutedForeground)}</string>
		<key>xcode.syntax.markup.code</key>
		<string>${colorValue(ansi.cyan)}</string>
		<key>xcode.syntax.number</key>
		<string>${colorValue(ansi.magenta)}</string>
		<key>xcode.syntax.plain</key>
		<string>${colorValue(colors.foreground)}</string>
		<key>xcode.syntax.preprocessor</key>
		<string>${colorValue(ansi.cyan)}</string>
		<key>xcode.syntax.string</key>
		<string>${colorValue(ansi.green)}</string>
		<key>xcode.syntax.url</key>
		<string>${colorValue(colors.primary)}</string>
	</dict>
	<key>DVTSourceTextSyntaxFonts</key>
	<dict>
		<key>xcode.syntax.attribute</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.character</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.comment</key>
		<string>SFMono-RegularItalic - 11.0</string>
		<key>xcode.syntax.comment.doc</key>
		<string>SFMono-RegularItalic - 11.0</string>
		<key>xcode.syntax.comment.doc.keyword</key>
		<string>SFMono-BoldItalic - 11.0</string>
		<key>xcode.syntax.declaration.other</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.declaration.type</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.identifier.class</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.identifier.class.system</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.identifier.constant</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.identifier.constant.system</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.identifier.function</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.identifier.function.system</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.identifier.macro</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.identifier.macro.system</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.identifier.type</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.identifier.type.system</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.identifier.variable</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.identifier.variable.system</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.keyword</key>
		<string>SFMono-Bold - 11.0</string>
		<key>xcode.syntax.mark</key>
		<string>SFMono-Bold - 11.0</string>
		<key>xcode.syntax.markup.code</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.number</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.plain</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.preprocessor</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.string</key>
		<string>SFMono-Regular - 11.0</string>
		<key>xcode.syntax.url</key>
		<string>SFMono-Regular - 11.0</string>
	</dict>
</dict>
</plist>
`;

  return {
    filename: `${name}.xccolortheme`,
    content: plist,
    platform: "xcode",
  };
}
