/**
 * Generate all 13 theme ZIPs for Gumroad distribution
 * Run with: npx ts-node scripts/generate-all-themes.ts
 */

import * as fs from "fs";
import * as path from "path";
import JSZip from "jszip";

// Import theme registry and exporters
import { themeRegistry } from "../src/lib/themes/registry";
import { exportAll, getPlatformFolder } from "../src/lib/exporters";
import { hexToHsl } from "../src/lib/color-utils";
import type { ThemeConfig, ThemeColors } from "../src/lib/exporters/types";

const OUTPUT_DIR = path.join(__dirname, "..", "generated-themes");

/**
 * Convert hex colors from theme definition to HSL ThemeColors
 */
function themeColorsToConfig(
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    foreground: string;
    muted: string;
  },
  themeName: string,
  displayName: string,
  mode: "light" | "dark"
): ThemeConfig {
  const primary = hexToHsl(colors.primary);
  const secondary = hexToHsl(colors.secondary);
  const accent = hexToHsl(colors.accent);
  const background = hexToHsl(colors.background);
  const foreground = hexToHsl(colors.foreground);
  const muted = hexToHsl(colors.muted);

  const themeColors: ThemeColors = {
    primary,
    secondary,
    accent,
    background,
    foreground,
    muted,
    mutedForeground: {
      h: muted.h,
      s: Math.min(muted.s, 15),
      l: muted.l < 50 ? 65 : 45,
    },
    card: background,
    cardForeground: foreground,
    popover: background,
    popoverForeground: foreground,
    border: {
      h: muted.h,
      s: muted.s,
      l: muted.l < 50 ? muted.l + 10 : muted.l - 10,
    },
    input: muted,
    ring: primary,
    destructive: { h: 0, s: 100, l: 67 },
    destructiveForeground: foreground,
  };

  return {
    name: `${themeName}-${mode}`,
    displayName: `${displayName} ${mode === "light" ? "Light" : "Dark"}`,
    author: "Theme Bundle",
    colors: themeColors,
  };
}

/**
 * Generate README for a theme
 */
function generateReadme(themeName: string, description: string): string {
  return `# ${themeName} Theme Bundle

${description}

This package contains your theme exported for **19 platforms** in both **Light** and **Dark** modes.

## Folder Structure

\`\`\`
${themeName.toLowerCase().replace(/\s+/g, "-")}/
├── light/
│   ├── terminals/
│   ├── editors/
│   ├── browsers/
│   └── apps/
├── dark/
│   ├── terminals/
│   ├── editors/
│   ├── browsers/
│   └── apps/
└── README.md
\`\`\`

## Installation Guides

### Terminal Emulators
- **Alacritty**: Copy \`.toml\` to \`~/.config/alacritty/\` and import in config
- **iTerm2**: Double-click \`.itermcolors\` to import, then select in Preferences
- **Windows Terminal**: Add the scheme to your \`settings.json\`
- **Hyper**: Copy config to \`~/.hyper.js\`

### Code Editors
- **VS Code**: Copy folder to \`~/.vscode/extensions/\` or load unpacked
- **Sublime Text**: Copy \`.sublime-color-scheme\` to Packages/User
- **Vim/Neovim**: Copy to \`~/.vim/colors/\` or \`~/.config/nvim/colors/\`
- **JetBrains**: Import \`.icls\` via Settings > Editor > Color Scheme

### Browsers
- **Firefox**: Load as temporary extension via \`about:debugging\`
- **Chrome**: Load unpacked via \`chrome://extensions\` (dev mode)

### Apps
- **Slack**: Paste the theme string in Preferences > Themes > Custom
- **Raycast**: Double-click \`.raycasttheme\` to import
- **Insomnia**: Copy folder to Insomnia plugins directory

## Support

If you have any issues or questions:
- Email: support@theme-bundle-pro.xyz
- Website: https://theme-bundle-pro.xyz

## License

This theme is licensed for personal and commercial use.

---

Generated by Theme Bundle
https://theme-bundle-pro.xyz
`;
}

/**
 * Generate LICENSE file
 */
function generateLicense(themeName: string): string {
  return `# Theme Bundle License

## ${themeName} Theme

Copyright (c) ${new Date().getFullYear()} Theme Bundle

### License Grant

You are granted a non-exclusive, worldwide license to:

1. **Use** this theme for personal and commercial projects
2. **Modify** the theme files for your own use
3. **Include** this theme in products you distribute (with attribution)

### Restrictions

You may NOT:

1. **Resell** this theme or derivative works as a standalone product
2. **Redistribute** this theme in a theme marketplace or similar
3. **Remove** attribution or claim the theme as your original work

### No Warranty

This theme is provided "as is" without warranty of any kind.
Theme Bundle is not liable for any damages arising from use.

---

Thank you for supporting Theme Bundle!
`;
}

/**
 * Generate ZIP for a single theme (both light and dark)
 */
async function generateThemeZip(theme: typeof themeRegistry[0]): Promise<void> {
  console.log(`Generating ${theme.name}...`);

  const zip = new JSZip();

  // Generate light mode exports
  const lightConfig = themeColorsToConfig(
    theme.colors.light,
    theme.id,
    theme.name,
    "light"
  );
  const lightExports = exportAll(lightConfig);

  for (const result of lightExports) {
    const folderPath = getPlatformFolder(result.platform);
    const fullPath = result.subfolder
      ? `light/${folderPath}/${result.subfolder}/${result.filename}`
      : `light/${folderPath}/${result.filename}`;
    zip.file(fullPath, result.content);
  }

  // Generate dark mode exports
  const darkConfig = themeColorsToConfig(
    theme.colors.dark,
    theme.id,
    theme.name,
    "dark"
  );
  const darkExports = exportAll(darkConfig);

  for (const result of darkExports) {
    const folderPath = getPlatformFolder(result.platform);
    const fullPath = result.subfolder
      ? `dark/${folderPath}/${result.subfolder}/${result.filename}`
      : `dark/${folderPath}/${result.filename}`;
    zip.file(fullPath, result.content);
  }

  // Add README
  zip.file("README.md", generateReadme(theme.name, theme.description));

  // Add LICENSE
  zip.file("LICENSE.md", generateLicense(theme.name));

  // Generate ZIP buffer
  const zipBuffer = await zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 9 },
  });

  // Ensure output directory exists
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  // Write ZIP file
  const filename = `${theme.id}-theme.zip`;
  const filepath = path.join(OUTPUT_DIR, filename);
  fs.writeFileSync(filepath, zipBuffer);

  const sizeKB = (zipBuffer.length / 1024).toFixed(2);
  console.log(`  ✓ ${filename} (${sizeKB} KB)`);
}

/**
 * Generate all theme ZIPs
 */
async function main() {
  console.log("=".repeat(50));
  console.log("Theme Bundle - Generating All Theme ZIPs");
  console.log("=".repeat(50));
  console.log(`\nOutput directory: ${OUTPUT_DIR}\n`);

  for (const theme of themeRegistry) {
    await generateThemeZip(theme);
  }

  console.log("\n" + "=".repeat(50));
  console.log(`✓ Generated ${themeRegistry.length} theme ZIPs`);
  console.log(`  Location: ${OUTPUT_DIR}`);
  console.log("=".repeat(50));
}

main().catch(console.error);
