/**
 * Generate a single ZIP containing all 13 themes for Gumroad Full Bundle
 * Run with: npx tsx scripts/generate-bundle-zip.ts
 */

import * as fs from "fs";
import * as path from "path";
import JSZip from "jszip";

import { themeRegistry } from "../src/lib/themes/registry";
import { exportAll, getPlatformFolder } from "../src/lib/exporters";
import { hexToHsl } from "../src/lib/color-utils";
import type { ThemeConfig, ThemeColors } from "../src/lib/exporters/types";

const OUTPUT_DIR = path.join(__dirname, "..", "generated-themes");

/**
 * Convert hex colors from theme definition to HSL ThemeColors
 */
function themeColorsToConfig(
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    background: string;
    foreground: string;
    muted: string;
  },
  themeName: string,
  displayName: string,
  mode: "light" | "dark"
): ThemeConfig {
  const primary = hexToHsl(colors.primary);
  const secondary = hexToHsl(colors.secondary);
  const accent = hexToHsl(colors.accent);
  const background = hexToHsl(colors.background);
  const foreground = hexToHsl(colors.foreground);
  const muted = hexToHsl(colors.muted);

  const themeColors: ThemeColors = {
    primary,
    secondary,
    accent,
    background,
    foreground,
    muted,
    mutedForeground: {
      h: muted.h,
      s: Math.min(muted.s, 15),
      l: muted.l < 50 ? 65 : 45,
    },
    card: background,
    cardForeground: foreground,
    popover: background,
    popoverForeground: foreground,
    border: {
      h: muted.h,
      s: muted.s,
      l: muted.l < 50 ? muted.l + 10 : muted.l - 10,
    },
    input: muted,
    ring: primary,
    destructive: { h: 0, s: 100, l: 67 },
    destructiveForeground: foreground,
  };

  return {
    name: `${themeName}-${mode}`,
    displayName: `${displayName} ${mode === "light" ? "Light" : "Dark"}`,
    author: "Theme Bundle",
    colors: themeColors,
  };
}

/**
 * Generate main README for the bundle
 */
function generateBundleReadme(): string {
  const themeList = themeRegistry.map(t => `- **${t.name}**: ${t.description}`).join("\n");
  
  return `# Theme Package Pro - Full Bundle

Thank you for purchasing the Theme Package Pro Full Bundle!

This package contains **13 premium themes**, each with **Light** and **Dark** modes, exported for **19 platforms**.

## Included Themes

${themeList}

## Folder Structure

Each theme folder contains:
\`\`\`
theme-name/
├── light/
│   ├── terminals/
│   ├── editors/
│   ├── browsers/
│   └── apps/
├── dark/
│   ├── terminals/
│   ├── editors/
│   ├── browsers/
│   └── apps/
└── README.md
\`\`\`

## Supported Platforms

### Terminals (6)
- Alacritty, iTerm2, Windows Terminal, Hyper, GNOME Terminal, Terminal.app

### Editors (8)
- VS Code, JetBrains IDEs, Sublime Text, Vim/Neovim, Emacs, Notepad++, Xcode, Zed

### Browsers (2)
- Chrome, Firefox

### Apps (3)
- Slack, Raycast, Insomnia

## Bonus: Custom Theme

As a Full Bundle owner, you also have access to the **Theme Studio** to create a custom theme!

1. Check your email for a **6-digit access code**
2. Go to https://theme-bundle-pro.xyz/buyer
3. Enter your email and code
4. Customize your own theme (Light & Dark separately)
5. Download your custom bundle

## Support

- Email: support@theme-bundle-pro.xyz
- Website: https://theme-bundle-pro.xyz

## License

Licensed for personal and commercial use. See LICENSE.md in each theme folder.

---

Generated by Theme Bundle
https://theme-bundle-pro.xyz
`;
}

/**
 * Generate LICENSE file
 */
function generateLicense(): string {
  return `# Theme Package Pro License

Copyright (c) ${new Date().getFullYear()} Theme Bundle

## License Grant

You are granted a non-exclusive, worldwide license to:

1. **Use** these themes for personal and commercial projects
2. **Modify** the theme files for your own use
3. **Include** these themes in products you distribute (with attribution)

## Restrictions

You may NOT:

1. **Resell** these themes or derivative works as standalone products
2. **Redistribute** these themes in a theme marketplace or similar
3. **Remove** attribution or claim the themes as your original work

## No Warranty

These themes are provided "as is" without warranty of any kind.
Theme Bundle is not liable for any damages arising from use.

---

Thank you for supporting Theme Bundle!
`;
}

async function main() {
  console.log("=".repeat(50));
  console.log("Theme Package Pro - Generating Full Bundle ZIP");
  console.log("=".repeat(50));

  const zip = new JSZip();

  for (const theme of themeRegistry) {
    console.log(`Adding ${theme.name}...`);
    const themeFolder = theme.id;

    // Generate light mode exports
    const lightConfig = themeColorsToConfig(
      theme.colors.light,
      theme.id,
      theme.name,
      "light"
    );
    const lightExports = exportAll(lightConfig);

    for (const result of lightExports) {
      const folderPath = getPlatformFolder(result.platform);
      const fullPath = result.subfolder
        ? `${themeFolder}/light/${folderPath}/${result.subfolder}/${result.filename}`
        : `${themeFolder}/light/${folderPath}/${result.filename}`;
      zip.file(fullPath, result.content);
    }

    // Generate dark mode exports
    const darkConfig = themeColorsToConfig(
      theme.colors.dark,
      theme.id,
      theme.name,
      "dark"
    );
    const darkExports = exportAll(darkConfig);

    for (const result of darkExports) {
      const folderPath = getPlatformFolder(result.platform);
      const fullPath = result.subfolder
        ? `${themeFolder}/dark/${folderPath}/${result.subfolder}/${result.filename}`
        : `${themeFolder}/dark/${folderPath}/${result.filename}`;
      zip.file(fullPath, result.content);
    }

    // Add theme-specific README
    zip.file(`${themeFolder}/README.md`, `# ${theme.name}\n\n${theme.description}\n\nSee main README.md for installation instructions.`);
  }

  // Add main README
  zip.file("README.md", generateBundleReadme());

  // Add LICENSE
  zip.file("LICENSE.md", generateLicense());

  // Generate ZIP buffer
  console.log("\nCompressing...");
  const zipBuffer = await zip.generateAsync({
    type: "nodebuffer",
    compression: "DEFLATE",
    compressionOptions: { level: 9 },
  });

  // Ensure output directory exists
  if (!fs.existsSync(OUTPUT_DIR)) {
    fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  }

  // Write ZIP file
  const filename = "theme-package-pro-full-bundle.zip";
  const filepath = path.join(OUTPUT_DIR, filename);
  fs.writeFileSync(filepath, zipBuffer);

  const sizeMB = (zipBuffer.length / (1024 * 1024)).toFixed(2);
  console.log("\n" + "=".repeat(50));
  console.log(`✓ Generated: ${filename} (${sizeMB} MB)`);
  console.log(`  Location: ${filepath}`);
  console.log("=".repeat(50));
}

main().catch(console.error);
